# Generated by Django 4.0.6 on 2022-08-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='already_sell',
            field=models.BooleanField(default=False),
        ),
    ]
