# Generated by Django 4.0.6 on 2022-08-02 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Goods',
            new_name='goods',
        ),
    ]
